---
kind: pipeline
type: docker
name: arm64-build

platform:
  arch: arm64
  os: linux

steps:
  - name: build-pio
    image: uxian/pio-esp32
    commands:
      - pio run
    when:
      event:
        - pull_request
        - tag

  - name: docker-pr-build
    image: plugins/docker
    settings:
      dry_run: true
      repo: test
      tags:
        - ${DRONE_COMMIT_SHA}
    when:
      event:
        - pull_request

  - name: docker-tag-build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry:
        from_secret: docker_registry
      repo:
        from_secret: docker_repo
      tags:
        - latest
        - "${DRONE_TAG}"
    when:
      event:
        - tag

trigger:
  ref:
    include:
      - refs/pull/**
      - refs/tags/**