main: deps
	go build ./src/main/main.go

deps:
	go get github.com/pkg/errors
	go get golang.org/x/net/context
	go get github.com/go-ble/ble
	go get github.com/mgutz/logxi/v1
	go get golang.org/x/sys/unix
