version: "3.6"
services:
  telegraf:
    image: telegraf
    volumes:
    - ./telegraf:/etc/telegraf
    ports:
    - 8186:8186
  influxdb:
    image: influxdb
    ports:
    - 8086:8086
    volumes:
    - ./influxdb:/var/lib/influxdb
  chronograf:
    image: chronograf
    ports:
    - 8888:8888
    volumes:
    - ./chronograf:/var/lib/chronograf
    command: ["chronograf", "--influxdb-url=http://influxdb:8086"]
  kapacitor:
    image: kapacitor
    environment:
    - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    volumes:
    - ./kapacitor:/var/lib/kapacitor